model: 'fpn' #

n_batch: 300
n_epoch: 100
n_kfolds: 5

n_rules: 5
lr: 0.001

dataset_folder: 'blog' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['blog']

#logger
log_to_file: 'true' # 'false' 'true'