model: 'fpn' #

n_batch: 300
n_epoch: 200
n_kfolds: 10

n_rules: 20
lr: 0.001

dataset_folder: 'CASP' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['CASP']

#logger
log_to_file: 'true' # 'false' 'true'