model: 'fpn_mlp2' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 3000
n_epoch: 200
n_kfolds: 5
noise_level: 0.5

n_rules: 50
lr: 0.001

dataset_folder: 'coil20' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['coil20']

#logger
log_to_file: 'true' # 'false' 'true'