model: 'fpn_mlpB' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 30
n_epoch: 300
n_kfolds: 5

n_rules: 5
lr: 0.0005

dataset_folder: 'flowmeter' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['MeterD']

#logger
log_to_file: 'true' # 'false' 'true'