model: 'fpn_cov1d' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 2000
n_epoch: 200
n_kfolds: 5
noise_level: 0.5

n_rules: 20
lr: 0.001

dataset_folder: 'pie' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['PIE_all']

#logger
log_to_file: 'true' # 'false' 'true'