model: 'fpn' #

n_batch: 3000
n_epoch: 200
n_kfolds: 5

n_rules: 50
lr: 0.001

dataset_folder: 'sdd' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['SDD']

#logger
log_to_file: 'true' # 'false' 'true'